name: Dioxus Docs Kit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.91.0
        with:
          components: rustfmt
      - name: Check Format
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.91.0
        with:
          components: clippy
      - uses: rui314/setup-mold@v1
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Generate Tailwind CSS
        run: |
          bun install --frozen-lockfile
          bunx @tailwindcss/cli -i tailwind.css -o assets/tailwind.css
      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.91.0
      - name: Install cargo-machete
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - name: Check for unused dependencies
        run: cargo machete

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.91.0
      - uses: rui314/setup-mold@v1
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Generate Tailwind CSS
        run: |
          bun install --frozen-lockfile
          bunx @tailwindcss/cli -i tailwind.css -o assets/tailwind.css
      - name: Run unit tests
        run: cargo test --workspace

  build:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@1.91.0
        with:
          targets: wasm32-unknown-unknown
      - uses: rui314/setup-mold@v1
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dioxus CLI
        uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli@0.7.3

      - name: Generate Tailwind CSS
        run: |
          bun install --frozen-lockfile
          bunx @tailwindcss/cli -i tailwind.css -o assets/tailwind.css

      - name: Build
        run: dx bundle --web --release
